import {
  SiHtml5,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiMongoose,
  SiJsonwebtokens,
  SiGit,
  SiVscodium,
  SiFigma,
  SiVercel,
  SiRender,
  SiCss,
} from "react-icons/si";

// Override CSS3 mapping if it doesn't exist. SiCss is an alternative.
export const skillIconMap = {
  "HTML": <SiHtml5 />,
  "CSS": <SiCss />,
  "JavaScript": <SiJavascript />,
  "TypeScript": <SiTypescript />,
  "React.js": <SiReact />,
  "Next.js": <SiNextdotjs />,
  "Node.js": <SiNodedotjs />,
  "Express.js": <SiExpress />,
  "MongoDB": <SiMongodb />,
  "Mongoose": <SiMongoose />,
  "JWT": <SiJsonwebtokens />,
  "Git": <SiGit />,
  "VS Code": <SiVscodium />,
  "Figma": <SiFigma />,
  "Vercel": <SiVercel />,
  "Render": <SiRender />,
};
